### ISSUE TITLE
THE RACHEL ROSENTHAL COMPANY does not display after selecting type as education

### ISSUE THREAD

**Issue by vivafung** [civil-services/artsforla-asset-map#50]
Steps:
1. Select EXPO line, culver city  
2. Check detail of THE RACHEL ROSENTHAL COMPANY  
3. Select organization type as educational, sub type as ARTS EDUCATION

Results:
THE RACHEL ROSENTHAL COMPANY disappears. 

Expected:
THE RACHEL ROSENTHAL COMPANY should remain on the map since its type includes "ARTS EDUCATION"

![screen shot 2015-03-17 at 3 14 30 pm](https://cloud.githubusercontent.com/assets/5256943/6698762/00573638-ccb9-11e4-9cf9-742bcd8649c3.png)

**Comment by ChrisC** [comment]
actually shows up under ‘MULTI.’ this is a similar usability issue as selecting disciplines and expecting any result with the selected discipline (not just the ones that have only the single selected discipline)
